# Generated by Django 5.0.6 on 2024-06-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('category', models.IntegerField(choices=[(1, 'Fundraising'), (2, 'franchising'), (3, 'Insurance Sales'), (4, 'Financing business'), (5, 'Rental and leasing'), (6, 'Investments'), (7, 'Sale of advertising'), (8, 'Affiliate Marketing'), (9, 'Online shop'), (10, 'Lead generation'), (11, 'Freemium'), (12, 'Sale of hours'), (13, 'Sale of services'), (14, 'Sale of events'), (15, 'License/Member fees'), (16, 'Wholesale'), (17, 'Agent representation'), (18, 'Retail'), (19, 'Consignment'), (20, 'Subscriptions'), (21, 'Handling fees'), (22, 'Manufacturing'), (23, 'Contract Manufacturing'), (24, 'Licenses Production'), (25, 'Outsourcing'), (26, 'Royalty')])),
                ('amount', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
